modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/jsburger/Architects-Palette/issues"

[[mods]]
    modId="${mod_id}"
    namespace="architects_palette"
    version="${mod_version}"
    displayName="Architect's Palette"
    authors="${mod_authors}"
    description='''${mod_description}'''
    displayURL=""
    [[dependencies.${mod_id}]]
        modId="forge"
        mandatory=true
        versionRange="${forge_version_range}"
        ordering="NONE"